@echo off
setlocal

pushd "%~dp0"
echo Build Start!!!!!!!!!!!!!!!!!!!!

set "GCC12_BIN=E:\E_paper_tool\MounRiver\MounRiver_Studio\toolchain\RISC-V Embedded GCC12\bin"
if exist "%GCC12_BIN%\riscv-none-elf-gcc.exe" set "PATH=%GCC12_BIN%;%PATH%"

for %%i in ("%cd%\..\..") do set "PARENT_DIR=%%~fi"
set "WORK_PATH=%PARENT_DIR%"

set "VER=0"
set "U_VER=000"
set "FACTORY=ENABLE_SOFTWARE_TO_TDX"
set "CUSTOMER=1"
set "SCREEN_CHIP=INK_SCREEN_CHIP_UC"
set "FLASH_MODE=USB_EXTERN_FLASH_SAVE"
set "EPD_SCREEN=EPD_SCREEN_13D3_1200X1600_C6"
set "EPD_VENDOR=EPD_VENDOR_DKE"
set "EPD_SCREEN_TYPE=EPD_SCREEN_TYPE_T"
set "USER_CFLAGS=-DVER=%VER% -D%FACTORY% -DINK_SCREEN_CUSTOMER=%CUSTOMER% -DINK_SCREEN_CHIP=%SCREEN_CHIP% -D%EPD_SCREEN% -D%EPD_VENDOR% -DENABLE_SCREEN_COLOR_6 -D%FLASH_MODE% -D%EPD_SCREEN_TYPE%"

set "U_FACTORY=TDX"
set "U_SCREEN=13D3_1200X1600C6"
set "U_VENDOR=DKE01"

set "DEST_FILE_NAME=%U_FACTORY%_%U_SCREEN%_%U_VENDOR%_V%U_VER%"
set "OUT_DIR=%CD%\OUTPUT"
set "DEST_DIR=%OUT_DIR%\%DEST_FILE_NAME%"
set "SOURCE=%CD%\obj\BackupUpgrade_OTA.hex"
set "DEST_FILE=%DEST_DIR%\%DEST_FILE_NAME%.hex"

echo /************************************************************/
echo Build TDX CH585 Product Project
echo VER:                  %U_VER%
echo SCREEN:               %EPD_SCREEN%
echo VENDOR:               %EPD_VENDOR% ^(%U_VENDOR%^)
echo EPD_SCREEN_TYPE:      %EPD_SCREEN_TYPE%
echo OUT_FILE:             %DEST_FILE%
echo /************************************************************/

make -C obj clean
if errorlevel 1 (
    echo Build clean warning, continue build.
)

make -C obj all
if errorlevel 1 goto :error

if not exist "%OUT_DIR%" md "%OUT_DIR%" 2>nul
if errorlevel 1 goto :mkdir_error

if not exist "%DEST_DIR%" md "%DEST_DIR%" 2>nul
if errorlevel 1 goto :mkdir_error

copy /y "%SOURCE%" "%DEST_FILE%" >nul
if errorlevel 1 (
    echo failure: copy failure
    goto :error
)

echo Build Complete!!!!!!!!!!!!!!!!!!!!
echo APP HEX: %DEST_FILE%
echo Full BIN is not regenerated by this script; please merge IAP + JumpIAP + APP hex manually.
popd
exit /b 0

:mkdir_error
echo error: cannot mkdir output dir

:error
echo Build Failure!!!!!!!!!!!!!!!!!!!!
popd
exit /b 1
