#pragma once

#include <stddef.h>

#define FACTORY_WELCOME_MANIFEST_URL \
    "http://192.168.25.208/eframeres/inkora-preset-image.json"
#define FACTORY_WELCOME_LOCAL_FILE_URL_PREFIX \
    "http://192.168.25.208/eframeres/"
#define FACTORY_WELCOME_LOCAL_CANONICAL_FILE_URL_PREFIX \
    "http://192.168.25.208:80/eframeres/"
#define FACTORY_WELCOME_CANONICAL_MANIFEST_URL \
    "http://192.168.25.208:80/eframeres/inkora-preset-image.json"
#define FACTORY_WELCOME_DIRECTORY_NAME "welcome"
#define FACTORY_WELCOME_MANIFEST_FILE_NAME "welcome_Json.txt"

#define FACTORY_WELCOME_MANIFEST_MAX_SIZE 8192U
#define FACTORY_WELCOME_URL_MAX_SIZE 512U
#define FACTORY_WELCOME_FILE_NAME_MAX_SIZE 128U
#define FACTORY_WELCOME_MAX_FILES 8U
#define FACTORY_WELCOME_MAX_COMPRESSED_SIZE (2U * 1024U * 1024U)

#define FACTORY_WELCOME_SD_READY_WAIT_MS 5000U
#define FACTORY_WELCOME_SD_READY_POLL_MS 100U
#define FACTORY_WELCOME_HTTP_TIMEOUT_MS 5000U
#define FACTORY_WELCOME_HTTP_RETRY_COUNT 2U
#define FACTORY_WELCOME_HTTP_RETRY_DELAY_MS 1000U
#define FACTORY_WELCOME_TOTAL_TIMEOUT_MS 20000U
